### ISSUE TITLE
Fix user details

### ISSUE THREAD

**Issue by MichaelCurrin** [rawho/githubstats#2]
I liked up my profile and still saw your username as my handle.

Also would like to see my actual website URL not the word website 

It would be cleaner to have a space before the bracket at `(@username)`. Or even take out username there and leave name since are duplicating the username below with the github logo.

![20201026_094253](https://user-images.githubusercontent.com/18750745/97146379-6a2c5b80-1770-11eb-9096-07833dd1e6a8.jpg)

**Comment by rawho** [comment]
Thank you for making me aware of this issue. 
The issue is solved, You can check it out now

**Comment by MichaelCurrin** [comment]
Thanks looks good. 👍
